### ISSUE TITLE
issue with einsum('mp,mq->mpq',mat,mat) behavior in comparison with python einsum()

### ISSUE THREAD

**Issue by takiy-berrandou** [const-ae/einsum#3]
Hi
Congrats for this package. I saw that was already available on CRAN.
I would to thank you for filling this gap in R as this function is really useful.
However, I spotted some different behavior in comparison with einsum() from numpy.
The following script (see bellow)example illustrate this discrepancy. I hope this can be helpful.  However, this is maybe a total error of my part, So I'll appreciate any answer and explanation.

Kind regards

Takiy

########################################################################################
### python
```
import numpy as np
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
```
##########################################
```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```
##########################################
#### 1/
`np.einsum('mp,mq->mq',mat,mat)`
###########################################
```
array([[  6,  12,  18],
       [ 60,  75,  90],
       [168, 192, 216]])
```
###########################################
`# identical to einsum() in R`
###########################################

#### 2/
`np.einsum('mp,mq->mpq',mat,mat)`
###########################################
```
array([[[ 1,  2,  3],
        [ 2,  4,  6],
        [ 3,  6,  9]],

       [[16, 20, 24],
        [20, 25, 30],
        [24, 30, 36]],

       [[49, 56, 63],
        [56, 64, 72],
        [63, 72, 81]]])
```
##########################################
`# not identical to einsum() in R`
###########################################

### R
```
library(einsum)
mat=matrix(1:9,ncol=3,byrow=T)
mat
```
##########################################
```
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
```
##########################################

#### 1/
`einsum('mp,mq->mq',mat,mat)`
#########################################
```
     [,1] [,2] [,3]
[1,]    6   12   18
[2,]   60   75   90
[3,]  168  192  216
```
#########################################
`# identical to einsum() in python`
###########################################

#### 2/
`einsum('mp,mq->mpq',mat,mat)`
##########################################
```
, , 1

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]   16   20   24
[3,]   49   56   63

, , 2

     [,1] [,2] [,3]
[1,]    2    4    6
[2,]   20   25   30
[3,]   56   64   72

, , 3

     [,1] [,2] [,3]
[1,]    3    6    9
[2,]   24   30   36
[3,]   63   72   81
```
##########################################
`# not identical to einsum() in python`
###########################################
########################################################################################

**Comment by const-ae** [comment]
Hi Takiy,

thanks for your interest in the package and for taking the time to compare it with python. I think the confusion comes from the fact that R and Python unfold multi-dimensional arrays differently when printing.

I created a small reprex to show that the results are equivalent:

``` r
library(reticulate)
py_run_string(r"( 
import numpy as np
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
np_result = np.einsum('mp,mq->mpq', mat, mat)                          
)")

print(py$mat)
#>      [,1] [,2] [,3]
#> [1,]    1    2    3
#> [2,]    4    5    6
#> [3,]    7    8    9
print(py$np_result)
#> , , 1
#> 
#>      [,1] [,2] [,3]
#> [1,]    1    2    3
#> [2,]   16   20   24
#> [3,]   49   56   63
#> 
#> , , 2
#> 
#>      [,1] [,2] [,3]
#> [1,]    2    4    6
#> [2,]   20   25   30
#> [3,]   56   64   72
#> 
#> , , 3
#> 
#>      [,1] [,2] [,3]
#> [1,]    3    6    9
#> [2,]   24   30   36
#> [3,]   63   72   81
r_res <- einsum::einsum('mp,mq->mpq', py$mat, py$mat)
r_res
#> , , 1
#> 
#>      [,1] [,2] [,3]
#> [1,]    1    2    3
#> [2,]   16   20   24
#> [3,]   49   56   63
#> 
#> , , 2
#> 
#>      [,1] [,2] [,3]
#> [1,]    2    4    6
#> [2,]   20   25   30
#> [3,]   56   64   72
#> 
#> , , 3
#> 
#>      [,1] [,2] [,3]
#> [1,]    3    6    9
#> [2,]   24   30   36
#> [3,]   63   72   81

testthat::expect_equal(py$np_result, r_res)
```

<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.3 (2020-10-10)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Berlin               
#>  date     2021-05-19                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
#>  callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.2)
#>  cli           2.2.0   2020-11-20 [1] CRAN (R 4.0.2)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
#>  devtools      2.3.2   2020-09-18 [1] CRAN (R 4.0.2)
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.2)
#>  einsum        0.1.0   2021-05-14 [1] local         
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
#>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.0)
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.0.2)
#>  jsonlite      1.7.1   2020-09-07 [1] CRAN (R 4.0.2)
#>  knitr         1.30    2020-09-22 [1] CRAN (R 4.0.2)
#>  lattice       0.20-41 2020-04-02 [1] CRAN (R 4.0.3)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.2)
#>  Matrix        1.2-18  2019-11-27 [1] CRAN (R 4.0.3)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
#>  pkgbuild      1.2.0   2021-01-04 [1] local         
#>  pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.2)
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
#>  processx      3.4.5   2020-11-30 [1] CRAN (R 4.0.2)
#>  ps            1.5.0   2020-12-05 [1] CRAN (R 4.0.3)
#>  R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.2)
#>  Rcpp          1.0.5   2020-07-06 [1] CRAN (R 4.0.2)
#>  remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
#>  reticulate  * 1.18    2020-10-25 [1] CRAN (R 4.0.2)
#>  rlang         0.4.9   2020-11-26 [1] CRAN (R 4.0.2)
#>  rmarkdown     2.6     2020-12-14 [1] CRAN (R 4.0.2)
#>  rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.2)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
#>  testthat      3.0.0   2020-10-31 [1] CRAN (R 4.0.2)
#>  usethis       1.6.3   2020-09-17 [1] CRAN (R 4.0.2)
#>  withr         2.3.0   2020-09-22 [1] CRAN (R 4.0.2)
#>  xfun          0.20    2021-01-06 [1] CRAN (R 4.0.2)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

I hope this clarifies the issue. If not, feel free to comment :)

Best,
Constantin

**Comment by takiy-berrandou** [comment]
Thanks for your quick and detailed reply.
If i understand well for array with 3 matrices for example in python they are displayed in layer as rubicube. but in R its different.
So, I am wondering Is there a fix or additional command to restore the output in python fashion?
Thank you again

Best

Takiy

**Comment by const-ae** [comment]
This article from the `reticulate` package https://rstudio.github.io/reticulate/articles/arrays.html goes into quite some depth to explain the issue. I hope this answers your question :)

I will close this issue for now, as the problem does not seem to be coming from `einsum`. However, feel free to reopen, if you think that I misunderstood something and there is a bug in `einsum`.
